# Output format — fast alert mode
output alert_fast: snort.alert

# Network configuration
var HOME_NET 192.168.198.0/24
var EXTERNAL_NET !$HOME_NET

# Rules
include $RULE_PATH/community.rules
include $RULE_PATH/local.rules
