input {
  beats {
    port => 5044
    ssl_enabled => false
  }
}

filter {
  if [fields][event][module] == "wazuh" {
    json {
      source => "message"
      target => "wazuh"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "wazuh-alerts-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
